#!/usr/bin/env python3
"""Materialize placeholder entity notes from unresolved links in ClawVault graph.

This is used after `clawvault graph --refresh` to create lightweight notes for
unresolved graph nodes so future link resolution becomes stable.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
import sys
import yaml

FIELD_TO_FOLDER = {
    "people": "people",
    "owner": "people",
    "project": "projects",
    "projects": "projects",
    "related": "topics",
    "topics": "topics",
    "depends_on": "topics",
    "dependsOn": "topics",
    "blocked_by": "topics",
    "blocks": "topics",
}


def to_slug(value: str) -> str:
    value = (value or "").strip().lower()
    value = re.sub(r"\.(md|markdown)$", "", value, flags=re.IGNORECASE)
    # Keep canonical slugs aligned with vault frontmatter policy.
    value = re.sub(r"[^a-z0-9\s_-]", "", value)
    value = re.sub(r"\s+", "-", value.strip())
    value = re.sub(r"-+", "-", value).strip("-")
    return value or "untitled"


def to_note_file(target: str, folder: str) -> Path:
    slug = to_slug(target)
    return Path(folder) / f"{slug}.md"


def write_note(path: Path, title: str, source: str) -> bool:
    if path.exists():
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    fm = {
        "title": title,
        "memoryType": "note",
        "source": source,
        "status": "active",
        "autoGenerated": True,
    }
    content = "---\n"
    content += yaml.safe_dump(fm, allow_unicode=True, sort_keys=False)
    content += "---\n\n"
    content += f"Nota materializada automaticamente para resolver link: {title}.\n"
    path.write_text(content, encoding="utf-8")
    return True


def extract_unresolved_label(target: str) -> str | None:
    # target format: unresolved:<key>
    if not target.startswith("unresolved:"):
        return None
    return target.removeprefix("unresolved:").replace("/", "-")


def relation_label_from_edge(edge: dict) -> str | None:
    lbl = edge.get("label")
    if isinstance(lbl, str) and lbl.strip():
        return lbl.strip()

    e_id = edge.get("id", "")
    parts = str(e_id).split(":")
    if len(parts) >= 2 and parts[-1] and not parts[-1].startswith("wiki"):
        # frontmatter_relation:id->target:field
        return parts[-1]
    return None


def has_existing_entity(vault: Path, field: str, target_slug: str) -> bool:
    folder = FIELD_TO_FOLDER.get(field)
    if not folder:
        return False
    return (vault / folder / f"{target_slug}.md").exists()


def process_graph(vault: Path, include_wiki: bool = True, canonical: bool = False):
    graph_path = vault / ".clawvault" / "graph-index.json"
    data = json.loads(graph_path.read_text(encoding="utf-8"))
    edges = data.get("graph", {}).get("edges", [])

    created = {"people": 0, "projects": 0, "topics": 0, "notes": 0}
    skipped = {"people": 0, "projects": 0, "topics": 0, "notes": 0}

    for edge in edges:
        e_type = edge.get("type", "")
        target = edge.get("target", "")
        if not str(target).startswith("unresolved:"):
            continue

        if e_type == "frontmatter_relation":
            field = relation_label_from_edge(edge)
            if not field or field not in FIELD_TO_FOLDER:
                continue
        elif e_type == "wiki_link" and include_wiki and not canonical:
            field = "wiki"
        else:
            continue

        target_title = extract_unresolved_label(target)
        if not target_title:
            continue
        normalized = target_title.strip().lower().replace(" ", "-")
        tail = re.split(r"[\-/]", normalized)[-1]
        if tail in {"untitled", "unknown"}:
            continue

        slug = to_slug(target_title)
        folder = FIELD_TO_FOLDER.get(field, "notes")

        if canonical:
            if not has_existing_entity(vault, field, slug):
                skipped[folder] = skipped.get(folder, 0) + 1
                continue

        note_path = vault / folder / f"{slug}.md"
        if write_note(note_path, target_title, source=f"clawvault:{e_type}:{field}"):
            created[folder] = created.get(folder, 0) + 1

    return {"created": created, "skipped": skipped}


def main():
    parser = argparse.ArgumentParser(description="Materialize unresolved graph nodes")
    parser.add_argument("--vault", required=True, help="Obsidian vault path")
    parser.add_argument("--dry-run", action="store_true", help="Report count only")
    parser.add_argument("--no-wiki", action="store_true", help="Ignore unresolved wiki links")
    parser.add_argument("--canonical", action="store_true", help="Process only already existing ontology entities by slug (strict mode)")
    args = parser.parse_args()

    vault = Path(args.vault).expanduser().resolve()

    # If not actually writing files, just emulate by recounting unresolved targets.
    if args.dry_run:
        idx = json.loads((vault / ".clawvault" / "graph-index.json").read_text(encoding="utf-8"))
        edges = idx.get("graph", {}).get("edges", [])
        count = {"people": 0, "projects": 0, "topics": 0, "notes": 0}
        for e in edges:
            if not str(e.get("target", "")).startswith("unresolved:"):
                continue
            e_type = e.get("type")
            if e_type == "frontmatter_relation":
                field = relation_label_from_edge(e)
                if not field or field not in FIELD_TO_FOLDER:
                    continue
            elif e_type == "wiki_link" and not args.no_wiki and not args.canonical:
                field = "wiki"
            else:
                continue

            target_title = extract_unresolved_label(str(e.get("target", "")))
            if not target_title:
                continue
            normalized = target_title.strip().lower().replace(" ", "-")
            slug = to_slug(target_title)
            tail = re.split(r"[\-/]", normalized)[-1]
            if tail in {"untitled", "unknown"}:
                continue

            if args.canonical:
                folder = FIELD_TO_FOLDER.get(field, "notes")
                if not has_existing_entity(vault, field, slug):
                    count[folder] = count.get(folder, 0) + 1
                    continue

            folder = FIELD_TO_FOLDER.get(field, "notes")
            count[folder] = count.get(folder, 0) + 1
        print(json.dumps({"dry_run": True, "counts": count}, ensure_ascii=False, indent=2))
        return

    result = process_graph(vault, include_wiki=not args.no_wiki, canonical=args.canonical)
    print(json.dumps({"dry_run": False, **result}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        raise SystemExit(1)
